/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuienesSomosRouteImport } from './routes/quienes-somos'
import { Route as ProgramasRouteImport } from './routes/programas'
import { Route as JovenYFuerteRouteImport } from './routes/joven-y-fuerte'
import { Route as InvestigacionRouteImport } from './routes/investigacion'
import { Route as InformadaSoyFuerteRouteImport } from './routes/informada-soy-fuerte'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as ColaboradoresRouteImport } from './routes/colaboradores'
import { Route as IndexRouteImport } from './routes/index'
import { Route as YoutubeYtIdRouteImport } from './routes/youtube.$ytId'
import { Route as VideoVimeoIdRouteImport } from './routes/video.$vimeoId'
import { Route as SociosSlugRouteImport } from './routes/socios.$slug'
import { Route as JovenYFuerteTratamientoRouteImport } from './routes/joven-y-fuerte_.tratamiento'
import { Route as JovenYFuerteTestimoniosRouteImport } from './routes/joven-y-fuerte_.testimonios'
import { Route as JovenYFuerteSupervivenciaRouteImport } from './routes/joven-y-fuerte_.supervivencia'
import { Route as JovenYFuertePacientesRouteImport } from './routes/joven-y-fuerte_.pacientes'
import { Route as JovenYFuerteEstiloDeVidaRouteImport } from './routes/joven-y-fuerte_.estilo-de-vida'
import { Route as JovenYFuerteDiagnosticoRouteImport } from './routes/joven-y-fuerte_.diagnostico'
import { Route as JovenYFuerteAspectosRelevantesRouteImport } from './routes/joven-y-fuerte_.aspectos-relevantes'
import { Route as JovenYFuerteAspectosPsicologicosRouteImport } from './routes/joven-y-fuerte_.aspectos-psicologicos'
import { Route as InvestigacionPremiosRouteImport } from './routes/investigacion_.premios'
import { Route as InvestigacionLibrosRouteImport } from './routes/investigacion_.libros'
import { Route as InvestigacionGicamxRouteImport } from './routes/investigacion_.gicamx'
import { Route as InvestigacionArticulosCientificosRouteImport } from './routes/investigacion_.articulos-cientificos'
import { Route as InformadaSoyFuerteTratamientoRouteImport } from './routes/informada-soy-fuerte_.tratamiento'
import { Route as InformadaSoyFuerteSobrevidaRouteImport } from './routes/informada-soy-fuerte_.sobrevida'
import { Route as InformadaSoyFuerteDiagnosticoRouteImport } from './routes/informada-soy-fuerte_.diagnostico'
import { Route as InformadaSoyFuerteDeteccionOportunaRouteImport } from './routes/informada-soy-fuerte_.deteccion-oportuna'
import { Route as InformadaSoyFuerteDeteccionOportunaVideoRouteImport } from './routes/informada-soy-fuerte_.deteccion-oportuna.video'

const QuienesSomosRoute = QuienesSomosRouteImport.update({
  id: '/quienes-somos',
  path: '/quienes-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramasRoute = ProgramasRouteImport.update({
  id: '/programas',
  path: '/programas',
  getParentRoute: () => rootRouteImport,
} as any)
const JovenYFuerteRoute = JovenYFuerteRouteImport.update({
  id: '/joven-y-fuerte',
  path: '/joven-y-fuerte',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigacionRoute = InvestigacionRouteImport.update({
  id: '/investigacion',
  path: '/investigacion',
  getParentRoute: () => rootRouteImport,
} as any)
const InformadaSoyFuerteRoute = InformadaSoyFuerteRouteImport.update({
  id: '/informada-soy-fuerte',
  path: '/informada-soy-fuerte',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const ColaboradoresRoute = ColaboradoresRouteImport.update({
  id: '/colaboradores',
  path: '/colaboradores',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const YoutubeYtIdRoute = YoutubeYtIdRouteImport.update({
  id: '/youtube/$ytId',
  path: '/youtube/$ytId',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoVimeoIdRoute = VideoVimeoIdRouteImport.update({
  id: '/video/$vimeoId',
  path: '/video/$vimeoId',
  getParentRoute: () => rootRouteImport,
} as any)
const SociosSlugRoute = SociosSlugRouteImport.update({
  id: '/socios/$slug',
  path: '/socios/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JovenYFuerteTratamientoRoute = JovenYFuerteTratamientoRouteImport.update({
  id: '/joven-y-fuerte_/tratamiento',
  path: '/joven-y-fuerte/tratamiento',
  getParentRoute: () => rootRouteImport,
} as any)
const JovenYFuerteTestimoniosRoute = JovenYFuerteTestimoniosRouteImport.update({
  id: '/joven-y-fuerte_/testimonios',
  path: '/joven-y-fuerte/testimonios',
  getParentRoute: () => rootRouteImport,
} as any)
const JovenYFuerteSupervivenciaRoute =
  JovenYFuerteSupervivenciaRouteImport.update({
    id: '/joven-y-fuerte_/supervivencia',
    path: '/joven-y-fuerte/supervivencia',
    getParentRoute: () => rootRouteImport,
  } as any)
const JovenYFuertePacientesRoute = JovenYFuertePacientesRouteImport.update({
  id: '/joven-y-fuerte_/pacientes',
  path: '/joven-y-fuerte/pacientes',
  getParentRoute: () => rootRouteImport,
} as any)
const JovenYFuerteEstiloDeVidaRoute =
  JovenYFuerteEstiloDeVidaRouteImport.update({
    id: '/joven-y-fuerte_/estilo-de-vida',
    path: '/joven-y-fuerte/estilo-de-vida',
    getParentRoute: () => rootRouteImport,
  } as any)
const JovenYFuerteDiagnosticoRoute = JovenYFuerteDiagnosticoRouteImport.update({
  id: '/joven-y-fuerte_/diagnostico',
  path: '/joven-y-fuerte/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const JovenYFuerteAspectosRelevantesRoute =
  JovenYFuerteAspectosRelevantesRouteImport.update({
    id: '/joven-y-fuerte_/aspectos-relevantes',
    path: '/joven-y-fuerte/aspectos-relevantes',
    getParentRoute: () => rootRouteImport,
  } as any)
const JovenYFuerteAspectosPsicologicosRoute =
  JovenYFuerteAspectosPsicologicosRouteImport.update({
    id: '/joven-y-fuerte_/aspectos-psicologicos',
    path: '/joven-y-fuerte/aspectos-psicologicos',
    getParentRoute: () => rootRouteImport,
  } as any)
const InvestigacionPremiosRoute = InvestigacionPremiosRouteImport.update({
  id: '/investigacion_/premios',
  path: '/investigacion/premios',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigacionLibrosRoute = InvestigacionLibrosRouteImport.update({
  id: '/investigacion_/libros',
  path: '/investigacion/libros',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigacionGicamxRoute = InvestigacionGicamxRouteImport.update({
  id: '/investigacion_/gicamx',
  path: '/investigacion/gicamx',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigacionArticulosCientificosRoute =
  InvestigacionArticulosCientificosRouteImport.update({
    id: '/investigacion_/articulos-cientificos',
    path: '/investigacion/articulos-cientificos',
    getParentRoute: () => rootRouteImport,
  } as any)
const InformadaSoyFuerteTratamientoRoute =
  InformadaSoyFuerteTratamientoRouteImport.update({
    id: '/informada-soy-fuerte_/tratamiento',
    path: '/informada-soy-fuerte/tratamiento',
    getParentRoute: () => rootRouteImport,
  } as any)
const InformadaSoyFuerteSobrevidaRoute =
  InformadaSoyFuerteSobrevidaRouteImport.update({
    id: '/informada-soy-fuerte_/sobrevida',
    path: '/informada-soy-fuerte/sobrevida',
    getParentRoute: () => rootRouteImport,
  } as any)
const InformadaSoyFuerteDiagnosticoRoute =
  InformadaSoyFuerteDiagnosticoRouteImport.update({
    id: '/informada-soy-fuerte_/diagnostico',
    path: '/informada-soy-fuerte/diagnostico',
    getParentRoute: () => rootRouteImport,
  } as any)
const InformadaSoyFuerteDeteccionOportunaRoute =
  InformadaSoyFuerteDeteccionOportunaRouteImport.update({
    id: '/informada-soy-fuerte_/deteccion-oportuna',
    path: '/informada-soy-fuerte/deteccion-oportuna',
    getParentRoute: () => rootRouteImport,
  } as any)
const InformadaSoyFuerteDeteccionOportunaVideoRoute =
  InformadaSoyFuerteDeteccionOportunaVideoRouteImport.update({
    id: '/video',
    path: '/video',
    getParentRoute: () => InformadaSoyFuerteDeteccionOportunaRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/colaboradores': typeof ColaboradoresRoute
  '/contacto': typeof ContactoRoute
  '/informada-soy-fuerte': typeof InformadaSoyFuerteRoute
  '/investigacion': typeof InvestigacionRoute
  '/joven-y-fuerte': typeof JovenYFuerteRoute
  '/programas': typeof ProgramasRoute
  '/quienes-somos': typeof QuienesSomosRoute
  '/informada-soy-fuerte/deteccion-oportuna': typeof InformadaSoyFuerteDeteccionOportunaRouteWithChildren
  '/informada-soy-fuerte/diagnostico': typeof InformadaSoyFuerteDiagnosticoRoute
  '/informada-soy-fuerte/sobrevida': typeof InformadaSoyFuerteSobrevidaRoute
  '/informada-soy-fuerte/tratamiento': typeof InformadaSoyFuerteTratamientoRoute
  '/investigacion/articulos-cientificos': typeof InvestigacionArticulosCientificosRoute
  '/investigacion/gicamx': typeof InvestigacionGicamxRoute
  '/investigacion/libros': typeof InvestigacionLibrosRoute
  '/investigacion/premios': typeof InvestigacionPremiosRoute
  '/joven-y-fuerte/aspectos-psicologicos': typeof JovenYFuerteAspectosPsicologicosRoute
  '/joven-y-fuerte/aspectos-relevantes': typeof JovenYFuerteAspectosRelevantesRoute
  '/joven-y-fuerte/diagnostico': typeof JovenYFuerteDiagnosticoRoute
  '/joven-y-fuerte/estilo-de-vida': typeof JovenYFuerteEstiloDeVidaRoute
  '/joven-y-fuerte/pacientes': typeof JovenYFuertePacientesRoute
  '/joven-y-fuerte/supervivencia': typeof JovenYFuerteSupervivenciaRoute
  '/joven-y-fuerte/testimonios': typeof JovenYFuerteTestimoniosRoute
  '/joven-y-fuerte/tratamiento': typeof JovenYFuerteTratamientoRoute
  '/socios/$slug': typeof SociosSlugRoute
  '/video/$vimeoId': typeof VideoVimeoIdRoute
  '/youtube/$ytId': typeof YoutubeYtIdRoute
  '/informada-soy-fuerte/deteccion-oportuna/video': typeof InformadaSoyFuerteDeteccionOportunaVideoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/colaboradores': typeof ColaboradoresRoute
  '/contacto': typeof ContactoRoute
  '/informada-soy-fuerte': typeof InformadaSoyFuerteRoute
  '/investigacion': typeof InvestigacionRoute
  '/joven-y-fuerte': typeof JovenYFuerteRoute
  '/programas': typeof ProgramasRoute
  '/quienes-somos': typeof QuienesSomosRoute
  '/informada-soy-fuerte/deteccion-oportuna': typeof InformadaSoyFuerteDeteccionOportunaRouteWithChildren
  '/informada-soy-fuerte/diagnostico': typeof InformadaSoyFuerteDiagnosticoRoute
  '/informada-soy-fuerte/sobrevida': typeof InformadaSoyFuerteSobrevidaRoute
  '/informada-soy-fuerte/tratamiento': typeof InformadaSoyFuerteTratamientoRoute
  '/investigacion/articulos-cientificos': typeof InvestigacionArticulosCientificosRoute
  '/investigacion/gicamx': typeof InvestigacionGicamxRoute
  '/investigacion/libros': typeof InvestigacionLibrosRoute
  '/investigacion/premios': typeof InvestigacionPremiosRoute
  '/joven-y-fuerte/aspectos-psicologicos': typeof JovenYFuerteAspectosPsicologicosRoute
  '/joven-y-fuerte/aspectos-relevantes': typeof JovenYFuerteAspectosRelevantesRoute
  '/joven-y-fuerte/diagnostico': typeof JovenYFuerteDiagnosticoRoute
  '/joven-y-fuerte/estilo-de-vida': typeof JovenYFuerteEstiloDeVidaRoute
  '/joven-y-fuerte/pacientes': typeof JovenYFuertePacientesRoute
  '/joven-y-fuerte/supervivencia': typeof JovenYFuerteSupervivenciaRoute
  '/joven-y-fuerte/testimonios': typeof JovenYFuerteTestimoniosRoute
  '/joven-y-fuerte/tratamiento': typeof JovenYFuerteTratamientoRoute
  '/socios/$slug': typeof SociosSlugRoute
  '/video/$vimeoId': typeof VideoVimeoIdRoute
  '/youtube/$ytId': typeof YoutubeYtIdRoute
  '/informada-soy-fuerte/deteccion-oportuna/video': typeof InformadaSoyFuerteDeteccionOportunaVideoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/colaboradores': typeof ColaboradoresRoute
  '/contacto': typeof ContactoRoute
  '/informada-soy-fuerte': typeof InformadaSoyFuerteRoute
  '/investigacion': typeof InvestigacionRoute
  '/joven-y-fuerte': typeof JovenYFuerteRoute
  '/programas': typeof ProgramasRoute
  '/quienes-somos': typeof QuienesSomosRoute
  '/informada-soy-fuerte_/deteccion-oportuna': typeof InformadaSoyFuerteDeteccionOportunaRouteWithChildren
  '/informada-soy-fuerte_/diagnostico': typeof InformadaSoyFuerteDiagnosticoRoute
  '/informada-soy-fuerte_/sobrevida': typeof InformadaSoyFuerteSobrevidaRoute
  '/informada-soy-fuerte_/tratamiento': typeof InformadaSoyFuerteTratamientoRoute
  '/investigacion_/articulos-cientificos': typeof InvestigacionArticulosCientificosRoute
  '/investigacion_/gicamx': typeof InvestigacionGicamxRoute
  '/investigacion_/libros': typeof InvestigacionLibrosRoute
  '/investigacion_/premios': typeof InvestigacionPremiosRoute
  '/joven-y-fuerte_/aspectos-psicologicos': typeof JovenYFuerteAspectosPsicologicosRoute
  '/joven-y-fuerte_/aspectos-relevantes': typeof JovenYFuerteAspectosRelevantesRoute
  '/joven-y-fuerte_/diagnostico': typeof JovenYFuerteDiagnosticoRoute
  '/joven-y-fuerte_/estilo-de-vida': typeof JovenYFuerteEstiloDeVidaRoute
  '/joven-y-fuerte_/pacientes': typeof JovenYFuertePacientesRoute
  '/joven-y-fuerte_/supervivencia': typeof JovenYFuerteSupervivenciaRoute
  '/joven-y-fuerte_/testimonios': typeof JovenYFuerteTestimoniosRoute
  '/joven-y-fuerte_/tratamiento': typeof JovenYFuerteTratamientoRoute
  '/socios/$slug': typeof SociosSlugRoute
  '/video/$vimeoId': typeof VideoVimeoIdRoute
  '/youtube/$ytId': typeof YoutubeYtIdRoute
  '/informada-soy-fuerte_/deteccion-oportuna/video': typeof InformadaSoyFuerteDeteccionOportunaVideoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/colaboradores'
    | '/contacto'
    | '/informada-soy-fuerte'
    | '/investigacion'
    | '/joven-y-fuerte'
    | '/programas'
    | '/quienes-somos'
    | '/informada-soy-fuerte/deteccion-oportuna'
    | '/informada-soy-fuerte/diagnostico'
    | '/informada-soy-fuerte/sobrevida'
    | '/informada-soy-fuerte/tratamiento'
    | '/investigacion/articulos-cientificos'
    | '/investigacion/gicamx'
    | '/investigacion/libros'
    | '/investigacion/premios'
    | '/joven-y-fuerte/aspectos-psicologicos'
    | '/joven-y-fuerte/aspectos-relevantes'
    | '/joven-y-fuerte/diagnostico'
    | '/joven-y-fuerte/estilo-de-vida'
    | '/joven-y-fuerte/pacientes'
    | '/joven-y-fuerte/supervivencia'
    | '/joven-y-fuerte/testimonios'
    | '/joven-y-fuerte/tratamiento'
    | '/socios/$slug'
    | '/video/$vimeoId'
    | '/youtube/$ytId'
    | '/informada-soy-fuerte/deteccion-oportuna/video'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/colaboradores'
    | '/contacto'
    | '/informada-soy-fuerte'
    | '/investigacion'
    | '/joven-y-fuerte'
    | '/programas'
    | '/quienes-somos'
    | '/informada-soy-fuerte/deteccion-oportuna'
    | '/informada-soy-fuerte/diagnostico'
    | '/informada-soy-fuerte/sobrevida'
    | '/informada-soy-fuerte/tratamiento'
    | '/investigacion/articulos-cientificos'
    | '/investigacion/gicamx'
    | '/investigacion/libros'
    | '/investigacion/premios'
    | '/joven-y-fuerte/aspectos-psicologicos'
    | '/joven-y-fuerte/aspectos-relevantes'
    | '/joven-y-fuerte/diagnostico'
    | '/joven-y-fuerte/estilo-de-vida'
    | '/joven-y-fuerte/pacientes'
    | '/joven-y-fuerte/supervivencia'
    | '/joven-y-fuerte/testimonios'
    | '/joven-y-fuerte/tratamiento'
    | '/socios/$slug'
    | '/video/$vimeoId'
    | '/youtube/$ytId'
    | '/informada-soy-fuerte/deteccion-oportuna/video'
  id:
    | '__root__'
    | '/'
    | '/colaboradores'
    | '/contacto'
    | '/informada-soy-fuerte'
    | '/investigacion'
    | '/joven-y-fuerte'
    | '/programas'
    | '/quienes-somos'
    | '/informada-soy-fuerte_/deteccion-oportuna'
    | '/informada-soy-fuerte_/diagnostico'
    | '/informada-soy-fuerte_/sobrevida'
    | '/informada-soy-fuerte_/tratamiento'
    | '/investigacion_/articulos-cientificos'
    | '/investigacion_/gicamx'
    | '/investigacion_/libros'
    | '/investigacion_/premios'
    | '/joven-y-fuerte_/aspectos-psicologicos'
    | '/joven-y-fuerte_/aspectos-relevantes'
    | '/joven-y-fuerte_/diagnostico'
    | '/joven-y-fuerte_/estilo-de-vida'
    | '/joven-y-fuerte_/pacientes'
    | '/joven-y-fuerte_/supervivencia'
    | '/joven-y-fuerte_/testimonios'
    | '/joven-y-fuerte_/tratamiento'
    | '/socios/$slug'
    | '/video/$vimeoId'
    | '/youtube/$ytId'
    | '/informada-soy-fuerte_/deteccion-oportuna/video'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ColaboradoresRoute: typeof ColaboradoresRoute
  ContactoRoute: typeof ContactoRoute
  InformadaSoyFuerteRoute: typeof InformadaSoyFuerteRoute
  InvestigacionRoute: typeof InvestigacionRoute
  JovenYFuerteRoute: typeof JovenYFuerteRoute
  ProgramasRoute: typeof ProgramasRoute
  QuienesSomosRoute: typeof QuienesSomosRoute
  InformadaSoyFuerteDeteccionOportunaRoute: typeof InformadaSoyFuerteDeteccionOportunaRouteWithChildren
  InformadaSoyFuerteDiagnosticoRoute: typeof InformadaSoyFuerteDiagnosticoRoute
  InformadaSoyFuerteSobrevidaRoute: typeof InformadaSoyFuerteSobrevidaRoute
  InformadaSoyFuerteTratamientoRoute: typeof InformadaSoyFuerteTratamientoRoute
  InvestigacionArticulosCientificosRoute: typeof InvestigacionArticulosCientificosRoute
  InvestigacionGicamxRoute: typeof InvestigacionGicamxRoute
  InvestigacionLibrosRoute: typeof InvestigacionLibrosRoute
  InvestigacionPremiosRoute: typeof InvestigacionPremiosRoute
  JovenYFuerteAspectosPsicologicosRoute: typeof JovenYFuerteAspectosPsicologicosRoute
  JovenYFuerteAspectosRelevantesRoute: typeof JovenYFuerteAspectosRelevantesRoute
  JovenYFuerteDiagnosticoRoute: typeof JovenYFuerteDiagnosticoRoute
  JovenYFuerteEstiloDeVidaRoute: typeof JovenYFuerteEstiloDeVidaRoute
  JovenYFuertePacientesRoute: typeof JovenYFuertePacientesRoute
  JovenYFuerteSupervivenciaRoute: typeof JovenYFuerteSupervivenciaRoute
  JovenYFuerteTestimoniosRoute: typeof JovenYFuerteTestimoniosRoute
  JovenYFuerteTratamientoRoute: typeof JovenYFuerteTratamientoRoute
  SociosSlugRoute: typeof SociosSlugRoute
  VideoVimeoIdRoute: typeof VideoVimeoIdRoute
  YoutubeYtIdRoute: typeof YoutubeYtIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quienes-somos': {
      id: '/quienes-somos'
      path: '/quienes-somos'
      fullPath: '/quienes-somos'
      preLoaderRoute: typeof QuienesSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programas': {
      id: '/programas'
      path: '/programas'
      fullPath: '/programas'
      preLoaderRoute: typeof ProgramasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/joven-y-fuerte': {
      id: '/joven-y-fuerte'
      path: '/joven-y-fuerte'
      fullPath: '/joven-y-fuerte'
      preLoaderRoute: typeof JovenYFuerteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigacion': {
      id: '/investigacion'
      path: '/investigacion'
      fullPath: '/investigacion'
      preLoaderRoute: typeof InvestigacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informada-soy-fuerte': {
      id: '/informada-soy-fuerte'
      path: '/informada-soy-fuerte'
      fullPath: '/informada-soy-fuerte'
      preLoaderRoute: typeof InformadaSoyFuerteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colaboradores': {
      id: '/colaboradores'
      path: '/colaboradores'
      fullPath: '/colaboradores'
      preLoaderRoute: typeof ColaboradoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/youtube/$ytId': {
      id: '/youtube/$ytId'
      path: '/youtube/$ytId'
      fullPath: '/youtube/$ytId'
      preLoaderRoute: typeof YoutubeYtIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video/$vimeoId': {
      id: '/video/$vimeoId'
      path: '/video/$vimeoId'
      fullPath: '/video/$vimeoId'
      preLoaderRoute: typeof VideoVimeoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/socios/$slug': {
      id: '/socios/$slug'
      path: '/socios/$slug'
      fullPath: '/socios/$slug'
      preLoaderRoute: typeof SociosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/joven-y-fuerte_/tratamiento': {
      id: '/joven-y-fuerte_/tratamiento'
      path: '/joven-y-fuerte/tratamiento'
      fullPath: '/joven-y-fuerte/tratamiento'
      preLoaderRoute: typeof JovenYFuerteTratamientoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/joven-y-fuerte_/testimonios': {
      id: '/joven-y-fuerte_/testimonios'
      path: '/joven-y-fuerte/testimonios'
      fullPath: '/joven-y-fuerte/testimonios'
      preLoaderRoute: typeof JovenYFuerteTestimoniosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/joven-y-fuerte_/supervivencia': {
      id: '/joven-y-fuerte_/supervivencia'
      path: '/joven-y-fuerte/supervivencia'
      fullPath: '/joven-y-fuerte/supervivencia'
      preLoaderRoute: typeof JovenYFuerteSupervivenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/joven-y-fuerte_/pacientes': {
      id: '/joven-y-fuerte_/pacientes'
      path: '/joven-y-fuerte/pacientes'
      fullPath: '/joven-y-fuerte/pacientes'
      preLoaderRoute: typeof JovenYFuertePacientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/joven-y-fuerte_/estilo-de-vida': {
      id: '/joven-y-fuerte_/estilo-de-vida'
      path: '/joven-y-fuerte/estilo-de-vida'
      fullPath: '/joven-y-fuerte/estilo-de-vida'
      preLoaderRoute: typeof JovenYFuerteEstiloDeVidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/joven-y-fuerte_/diagnostico': {
      id: '/joven-y-fuerte_/diagnostico'
      path: '/joven-y-fuerte/diagnostico'
      fullPath: '/joven-y-fuerte/diagnostico'
      preLoaderRoute: typeof JovenYFuerteDiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/joven-y-fuerte_/aspectos-relevantes': {
      id: '/joven-y-fuerte_/aspectos-relevantes'
      path: '/joven-y-fuerte/aspectos-relevantes'
      fullPath: '/joven-y-fuerte/aspectos-relevantes'
      preLoaderRoute: typeof JovenYFuerteAspectosRelevantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/joven-y-fuerte_/aspectos-psicologicos': {
      id: '/joven-y-fuerte_/aspectos-psicologicos'
      path: '/joven-y-fuerte/aspectos-psicologicos'
      fullPath: '/joven-y-fuerte/aspectos-psicologicos'
      preLoaderRoute: typeof JovenYFuerteAspectosPsicologicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigacion_/premios': {
      id: '/investigacion_/premios'
      path: '/investigacion/premios'
      fullPath: '/investigacion/premios'
      preLoaderRoute: typeof InvestigacionPremiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigacion_/libros': {
      id: '/investigacion_/libros'
      path: '/investigacion/libros'
      fullPath: '/investigacion/libros'
      preLoaderRoute: typeof InvestigacionLibrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigacion_/gicamx': {
      id: '/investigacion_/gicamx'
      path: '/investigacion/gicamx'
      fullPath: '/investigacion/gicamx'
      preLoaderRoute: typeof InvestigacionGicamxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigacion_/articulos-cientificos': {
      id: '/investigacion_/articulos-cientificos'
      path: '/investigacion/articulos-cientificos'
      fullPath: '/investigacion/articulos-cientificos'
      preLoaderRoute: typeof InvestigacionArticulosCientificosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informada-soy-fuerte_/tratamiento': {
      id: '/informada-soy-fuerte_/tratamiento'
      path: '/informada-soy-fuerte/tratamiento'
      fullPath: '/informada-soy-fuerte/tratamiento'
      preLoaderRoute: typeof InformadaSoyFuerteTratamientoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informada-soy-fuerte_/sobrevida': {
      id: '/informada-soy-fuerte_/sobrevida'
      path: '/informada-soy-fuerte/sobrevida'
      fullPath: '/informada-soy-fuerte/sobrevida'
      preLoaderRoute: typeof InformadaSoyFuerteSobrevidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informada-soy-fuerte_/diagnostico': {
      id: '/informada-soy-fuerte_/diagnostico'
      path: '/informada-soy-fuerte/diagnostico'
      fullPath: '/informada-soy-fuerte/diagnostico'
      preLoaderRoute: typeof InformadaSoyFuerteDiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informada-soy-fuerte_/deteccion-oportuna': {
      id: '/informada-soy-fuerte_/deteccion-oportuna'
      path: '/informada-soy-fuerte/deteccion-oportuna'
      fullPath: '/informada-soy-fuerte/deteccion-oportuna'
      preLoaderRoute: typeof InformadaSoyFuerteDeteccionOportunaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informada-soy-fuerte_/deteccion-oportuna/video': {
      id: '/informada-soy-fuerte_/deteccion-oportuna/video'
      path: '/video'
      fullPath: '/informada-soy-fuerte/deteccion-oportuna/video'
      preLoaderRoute: typeof InformadaSoyFuerteDeteccionOportunaVideoRouteImport
      parentRoute: typeof InformadaSoyFuerteDeteccionOportunaRoute
    }
  }
}

interface InformadaSoyFuerteDeteccionOportunaRouteChildren {
  InformadaSoyFuerteDeteccionOportunaVideoRoute: typeof InformadaSoyFuerteDeteccionOportunaVideoRoute
}

const InformadaSoyFuerteDeteccionOportunaRouteChildren: InformadaSoyFuerteDeteccionOportunaRouteChildren =
  {
    InformadaSoyFuerteDeteccionOportunaVideoRoute:
      InformadaSoyFuerteDeteccionOportunaVideoRoute,
  }

const InformadaSoyFuerteDeteccionOportunaRouteWithChildren =
  InformadaSoyFuerteDeteccionOportunaRoute._addFileChildren(
    InformadaSoyFuerteDeteccionOportunaRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ColaboradoresRoute: ColaboradoresRoute,
  ContactoRoute: ContactoRoute,
  InformadaSoyFuerteRoute: InformadaSoyFuerteRoute,
  InvestigacionRoute: InvestigacionRoute,
  JovenYFuerteRoute: JovenYFuerteRoute,
  ProgramasRoute: ProgramasRoute,
  QuienesSomosRoute: QuienesSomosRoute,
  InformadaSoyFuerteDeteccionOportunaRoute:
    InformadaSoyFuerteDeteccionOportunaRouteWithChildren,
  InformadaSoyFuerteDiagnosticoRoute: InformadaSoyFuerteDiagnosticoRoute,
  InformadaSoyFuerteSobrevidaRoute: InformadaSoyFuerteSobrevidaRoute,
  InformadaSoyFuerteTratamientoRoute: InformadaSoyFuerteTratamientoRoute,
  InvestigacionArticulosCientificosRoute:
    InvestigacionArticulosCientificosRoute,
  InvestigacionGicamxRoute: InvestigacionGicamxRoute,
  InvestigacionLibrosRoute: InvestigacionLibrosRoute,
  InvestigacionPremiosRoute: InvestigacionPremiosRoute,
  JovenYFuerteAspectosPsicologicosRoute: JovenYFuerteAspectosPsicologicosRoute,
  JovenYFuerteAspectosRelevantesRoute: JovenYFuerteAspectosRelevantesRoute,
  JovenYFuerteDiagnosticoRoute: JovenYFuerteDiagnosticoRoute,
  JovenYFuerteEstiloDeVidaRoute: JovenYFuerteEstiloDeVidaRoute,
  JovenYFuertePacientesRoute: JovenYFuertePacientesRoute,
  JovenYFuerteSupervivenciaRoute: JovenYFuerteSupervivenciaRoute,
  JovenYFuerteTestimoniosRoute: JovenYFuerteTestimoniosRoute,
  JovenYFuerteTratamientoRoute: JovenYFuerteTratamientoRoute,
  SociosSlugRoute: SociosSlugRoute,
  VideoVimeoIdRoute: VideoVimeoIdRoute,
  YoutubeYtIdRoute: YoutubeYtIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
<<<<<<< HEAD
=======

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
>>>>>>> 2cd7c657978e4915ff4086e40db8aaf03d0fa01d
